### ISSUE TITLE
ionic 3 syntax

### ISSUE THREAD

**Issue by Simpler1** [fabiorogeriosj/cordova-plugin-sensors#13]
What would be the syntax for implementing this with ionic 3?

Thanks

**Comment by fabiorogeriosj** [comment]
Hi, just use a pure JS, install the plugin and use in your controller.

**Comment by martinsebastien** [comment]
Hi @fabiorogeriosj , can you be more specific ? Thanks a lot

**Comment by fabiorogeriosj** [comment]
Hi @martinsebastien, you can use all plugins by cordova like this in ionic 3:

```
(<any>window).pluginName
```

Please, test like this for use a sensors:
```
(<any>window).sensors.enableSensor("PROXIMITY")
```
If this code work, send your feedback!

**Comment by martinsebastien** [comment]
This are the steps I did:
Install the plugin with :
`cordova plugin add https://github.com/fabiorogeriosj/cordova-plugin-sensors.git`

Then try to use it in my Home page : 
```
import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(
    public navCtrl: NavController,
    public platform: Platform
    ) {
      this.initSensor();
  }

  initSensor() {
    console.log((<any>window).sensors);
  }

}
```

But I a get undefined in the console. Did I miss something ?

Thank for your reply

**Comment by fabiorogeriosj** [comment]
Try this @martinsebastien :
```
console.log((<any>window).sensors)
```
add "s" in name plugin.

**Comment by martinsebastien** [comment]
It doesn't change anything, always undefined even with :  
```
    this.platform.ready().then(() => {
          console.log((<any>window).sensors);
    });

```

**Comment by fabiorogeriosj** [comment]
:(
Are you debugging in your device right @martinsebastien ? If yes I gonna test here in ionic 3.

**Comment by fabiorogeriosj** [comment]
Hi @martinsebastien, `<any>` worked for me, but have a another sintax:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Platform } from 'ionic-angular';

declare var sensors;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  proximity:number;

  constructor(public navCtrl: NavController, platform: Platform) {
    this.proximity = 0;
    
    platform.ready().then(() => {
      this.initSensor();
    })

  }

  initSensor() {
    sensors.enableSensor("PROXIMITY")
    
    setInterval(() => {
      sensors.getState((values) => {
        this.proximity = values[0]
      });
    }, 300)
    
  }

}
```

**Comment by fabiorogeriosj** [comment]
I added a complete example here: https://github.com/fabiorogeriosj/cordova-plugin-sensors-demo/tree/master/android/ionic3

**Comment by Simpler1** [comment]
I created the following Pull Request to incorporate this into ionic-native:
https://github.com/ionic-team/ionic-native/pull/2268

**Comment by martinsebastien** [comment]
Awesome, thank you very much! :)
